
export const FETCH_QT_ACCESS_REQUEST = 'FETCH_QT_ACCESS'
export const FETCH_QT_ACCESS_SUCCESS = 'FETCH_QT_ACCESS_SUCCESS'
export const FETCH_QT_ACCESS_FAILURE = 'FETCH_QT_ACCESS_FAILURE'

export const REFRESH_QT_ACCESS_REQUEST = 'REFRESH_QT_ACCESS_REQUEST'
export const REFRESH_QT_ACCESS_SUCCESS = 'REFRESH_QT_ACCESS_SUCCESS'
export const REFRESH_QT_ACCESS_FAILURE = 'REFRESH_QT_ACCESS_FAILURE'
