
export const QT_ACCESS_DIALOG_SHOW = 'QT_ACCESS_DIALOG_SHOW'
export const QT_ACCESS_DIALOG_HIDE = 'QT_ACCESS_DIALOG_HIDE'

export const ADD_QT_ACCESS_REQUEST = 'ADD_QT_ACCESS_REQUEST'
export const ADD_QT_ACCESS_SUCCESS = 'ADD_QT_ACCESS_SUCCESS'
export const ADD_QT_ACCESS_FAILURE = 'ADD_QT_ACCESS_FAILURE'

export const FETCH_QT_ACCESS_REQUEST = 'FETCH_QT_ACCESS_REQUEST'
export const FETCH_QT_ACCESS_SUCCESS = 'FETCH_QT_ACCESS_SUCCESS'
export const FETCH_QT_ACCESS_FAILURE = 'FETCH_QT_ACCESS_FAILURE'

export const REFRESH_QT_ACCESS_REQUEST = 'REFRESH_QT_ACCESS_REQUEST'
export const REFRESH_QT_ACCESS_SUCCESS = 'REFRESH_QT_ACCESS_SUCCESS'
export const REFRESH_QT_ACCESS_FAILURE = 'REFRESH_QT_ACCESS_FAILURE'
